# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-05 15:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SDP', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RightsSupport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'managed': False,
                'permissions': (('instructor', 'Instructor'), ('admin', 'Admin')),
            },
        ),
        migrations.AlterField(
            model_name='component',
            name='typ',
            field=models.CharField(choices=[('TX', 'Text'), ('IM', 'Image'), ('VD', 'Video'), ('FL', 'File')], default='TX', max_length=2),
        ),
    ]
